
// This file has been generated by the GUI designer. Do not modify.
namespace kspscience
{
	public partial class DeltaV
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget kspscience.DeltaV
			this.Name = "kspscience.DeltaV";
			this.Title = global::Mono.Unix.Catalog.GetString ("DeltaV");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
