
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.VBox vbox2;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Button button30;
	private global::Gtk.Button button31;
	private global::Gtk.Button button32;
	private global::Gtk.Button button33;
	private global::Gtk.Button button34;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Button button35;
	private global::Gtk.Button button37;
	private global::Gtk.Button button39;
	private global::Gtk.Button button41;
	private global::Gtk.Button button43;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Button button36;
	private global::Gtk.Button button38;
	private global::Gtk.Button button40;
	private global::Gtk.Button button42;
	private global::Gtk.Button button44;
	private global::Gtk.Fixed fixed1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'/></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox2.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button30 = new global::Gtk.Button ();
		this.button30.WidthRequest = 120;
		this.button30.CanFocus = true;
		this.button30.Name = "button30";
		this.button30.UseUnderline = true;
		this.button30.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox3.Add (this.button30);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button30]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button31 = new global::Gtk.Button ();
		this.button31.CanFocus = true;
		this.button31.Name = "button31";
		this.button31.UseUnderline = true;
		this.button31.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox3.Add (this.button31);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button31]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button32 = new global::Gtk.Button ();
		this.button32.CanFocus = true;
		this.button32.Name = "button32";
		this.button32.UseUnderline = true;
		this.button32.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox3.Add (this.button32);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button32]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button33 = new global::Gtk.Button ();
		this.button33.CanFocus = true;
		this.button33.Name = "button33";
		this.button33.UseUnderline = true;
		this.button33.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox3.Add (this.button33);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button33]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button34 = new global::Gtk.Button ();
		this.button34.CanFocus = true;
		this.button34.Name = "button34";
		this.button34.UseUnderline = true;
		this.button34.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox3.Add (this.button34);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button34]));
		w7.Position = 4;
		w7.Expand = false;
		w7.Fill = false;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button35 = new global::Gtk.Button ();
		this.button35.WidthRequest = 120;
		this.button35.CanFocus = true;
		this.button35.Name = "button35";
		this.button35.UseUnderline = true;
		this.button35.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox4.Add (this.button35);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button35]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button37 = new global::Gtk.Button ();
		this.button37.CanFocus = true;
		this.button37.Name = "button37";
		this.button37.UseUnderline = true;
		this.button37.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox4.Add (this.button37);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button37]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button39 = new global::Gtk.Button ();
		this.button39.CanFocus = true;
		this.button39.Name = "button39";
		this.button39.UseUnderline = true;
		this.button39.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox4.Add (this.button39);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button39]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button41 = new global::Gtk.Button ();
		this.button41.CanFocus = true;
		this.button41.Name = "button41";
		this.button41.UseUnderline = true;
		this.button41.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox4.Add (this.button41);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button41]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button43 = new global::Gtk.Button ();
		this.button43.CanFocus = true;
		this.button43.Name = "button43";
		this.button43.UseUnderline = true;
		this.button43.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox4.Add (this.button43);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button43]));
		w13.Position = 4;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.button36 = new global::Gtk.Button ();
		this.button36.WidthRequest = 120;
		this.button36.CanFocus = true;
		this.button36.Name = "button36";
		this.button36.UseUnderline = true;
		this.button36.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox5.Add (this.button36);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.button36]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.button38 = new global::Gtk.Button ();
		this.button38.CanFocus = true;
		this.button38.Name = "button38";
		this.button38.UseUnderline = true;
		this.button38.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox5.Add (this.button38);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.button38]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.button40 = new global::Gtk.Button ();
		this.button40.CanFocus = true;
		this.button40.Name = "button40";
		this.button40.UseUnderline = true;
		this.button40.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox5.Add (this.button40);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.button40]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.button42 = new global::Gtk.Button ();
		this.button42.CanFocus = true;
		this.button42.Name = "button42";
		this.button42.UseUnderline = true;
		this.button42.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox5.Add (this.button42);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.button42]));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.button44 = new global::Gtk.Button ();
		this.button44.CanFocus = true;
		this.button44.Name = "button44";
		this.button44.UseUnderline = true;
		this.button44.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox5.Add (this.button44);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.button44]));
		w19.Position = 4;
		w19.Expand = false;
		w19.Fill = false;
		this.hbox1.Add (this.vbox5);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox5]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.vbox2.Add (this.fixed1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.fixed1]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 378;
		this.DefaultHeight = 217;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
